### PR TITLE
Update SessionInfo data type and JSON parsing

### PR DESCRIPTION
**Pull request by ketzacoatl**
The "Checks" field has become "NodeChecks" and "ServiceChecks".

### CODE REVIEW

**Comment by ketzacoatl** [comment]
The CI jobs failing are a race condition with consul starting up and completing node registration for itself. The tests need to run with a short delay (though even with 2 seconds, I've seen failures once in a while).

**Comment by ketzacoatl** [comment]
This is a breaking change, consul version 1.6.2 will not pass tests with this update. Updated CI to run 1.9.0.

We should publish some sort of policy on backwards compatibility and the versions of consul we support.

**Comment by ketzacoatl** [comment]
I didn't mean to hit the close button..

**Comment by nh2** [comment]
Uh, I found that this fix may be correct only sometimes:

https://github.com/hashicorp/consul/issues/7341

Looks like since Consul 1.7 the documentation of what can be returned is incorrect/incomplete; from https://github.com/hashicorp/consul/issues/7341#issuecomment-625027010:

> It looks like `Checks` only disappears from the info response when the session was created with `Checks` set to the default value of `["serfHealth"]` (implicitly or explicitly). When the session is associated with additional checks they're returned in a `Checks` key when querying session info just as in previous Consul versions.

The corresponding commit from the Consul Perl bindings thus permit either way: https://github.com/robn/Consul/commit/e4db8457c377d13845559136c3e1f3c24e4ffba5

**Comment by ketzacoatl** [comment]
Do I understand correctly:
* In the JSON, we might get `Checks`, or `NodeChecks`, or `ServiceChecks` (well it sounds like we always get NodeChecks back now?)
* We need to keep a Maybe Checks to support that?

What would this support look like, or is it as simple as it sounds?

**Comment by nh2** [comment]
> We need to keep a Maybe Checks to support that?

Yes, I think it's best to have

```haskell
siChecks :: Maybe [Text], 
siNodeChecks :: Maybe [Text],
siServiceChecks :: Maybe [Text], 
```

with an added comment/link to this, until Consul clears up their docs.

**Comment by ketzacoatl** [comment]
OK, that's been resolved in #43.

**Pull request merged**
