### PR TITLE
Fixing compilation issues introduced by updated http client package.

### PR DESCRIPTION
**Pull request by jm4games**

### CODE REVIEW

**Comment by jm4games** [comment]
Build failed, looks like stack is limiting the version of http client package. When used with other non-stack projects this fails.

**Comment by sseveran** [comment]
I will look into this today. A cursory look makes me think that the library interface changed and we might need to add some ifdefs to handle different versions. LTS haskell including nightly is still on http-client 0.4 versions and since that is what we use internally I need it to remain supported. I have been meaning to make the build more flexible so we could build more versions in different configurations. The current build just shows what matters to me personally. If you don't mind sharing what GHC and lib versions your are building against I will see what we can do about having travis check that as well.

**Comment by jm4games** [comment]
Thx for quick response sseveran :). I totally agree with adding some ifdefs, I'll add some tweaks to my PR if you want that does this.

**Comment by sseveran** [comment]
Great. Go ahead and do that. I have updated the travis build to properly reflect the state of the world. https://travis-ci.org/alphaHeavy/consul-haskell

I don't know if you need to rebase on master to get travis to use the updated build configuration.

**Comment by sseveran** [comment]
I have fixed this and released 0.4.

**Comment by jm4games** [comment]
Cool thanks. Sorry I never got around to doing this. I couldn't come up with a trival way to do it :(

**Pull request closed without merging**
